### ISSUE TITLE
[BUG] can't compile on Android

### ISSUE THREAD

**Issue by marcoberetta96** [jhomlala/betterplayer#875]
**History check**
Done.

**Describe the bug**
When launching app on Android I get the following error.
```
.../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: package com.jhomlala.better_player does not exist
      flutterEngine.getPlugins().add(new com.jhomlala.better_player.BetterPlayerPlugin());
```

**Flutter doctor**
```
[✓] Flutter (Channel stable, 2.8.1)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (4 available)
```

**Better Player version**
- Version: 0.0.81

**Comment by hussenIbrahim** [comment]
i faced same issue with another package
what is your target and compile android SDK?

**Comment by marcoberetta96** [comment]
both 31

**Comment by shiyiya** [comment]
created by flutter 1？

**Comment by marcoberetta96** [comment]
Yes, initially created with flutter 1.
Now running with flutter 2.8.1.

**Comment by shiyiya** [comment]
try migrate to flutter 2.

**Comment by marcoberetta96** [comment]
@shiyiya what do you mean? I'm already on flutter 2.8.1

**Comment by shiyiya** [comment]
Can you post the MainActivity.kt file?

flutter 1 and 2 are not the same.

**Comment by marcoberetta96** [comment]
Here my `MainActivity.java`. Am I missing something?

```
package com.marco...;

import android.content.Context;
import android.graphics.Color;
import android.os.Bundle;
import android.os.Handler;
import android.text.Spannable;
import android.text.SpannableString;
import android.text.style.ForegroundColorSpan;
import android.util.Log;
import androidx.annotation.NonNull;
import com.onesignal.OSMutableNotification;
import com.onesignal.OSNotification;
import com.onesignal.OSNotificationReceivedEvent;
import com.onesignal.OneSignal.OSRemoteNotificationReceivedHandler;
import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugins.GeneratedPluginRegistrant;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import org.json.JSONObject;

public class MainActivity extends FlutterActivity {
    
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

```

**Comment by shiyiya** [comment]
Take a look at the official Flutter wiki:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by marcoberetta96** [comment]
Done, but issue is still the same. It happens only with this package.

```
/.../android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:24: error: package com.jhomlala.better_player does not exist
      flutterEngine.getPlugins().add(new com.jhomlala.better_player.BetterPlayerPlugin());
                                                                   ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

**Comment by shiyiya** [comment]
😕 i have not idea.

**Comment by marcoberetta96** [comment]
Still debugging...
Everything works with `better_player: 0.0.77`
Issue comes with `better_player: 0.0.78`

From the changelog I see 

- Migrated android native code to Kotlin.
- Updated ExoPlayer version to 2.15.1.

Maybe the cause is related to one of this...
@jhomlala do you have any idea?

**Comment by shiyiya** [comment]
https://github.com/jhomlala/betterplayer/issues/882#issuecomment-1012977577

**Comment by marcoberetta96** [comment]
@shiyiya solved! Thank you!!
